#pragma once

//////////////////////////////////////////////////////////////////////////
// CONTROL ID

#define IDC_BTN_SYS_CLOSE                   60001
#define IDC_BTN_SYS_MAX                     60002
#define IDC_BTN_SYS_MIN                     60003
#define IDC_LBL_MSGBOX_TITLE                60004
#define IDC_ICON_MSGBOX_ICON                60005
#define IDC_LBL_MSGBOX_TEXT                 60006
#define IDC_CHK_MSGBOX_NONOTIFYLATER        60007
#define IDC_DIV_MSGBOX_BUTTONS              60008
#define IDC_DIV_MSGBOX_CONTENT              60009
#define IDC_IMG_MSGBOX_PNG					60100

#define IDC_BTN_FAST_SCAN                       100
#define IDC_BTN_FULL_SCAN                       101
#define IDC_BTN_CUSTOM_SCAN                     102
#define IDC_DIV_VIRSCAN_SELECT_MODE             103
#define IDC_DIV_VIRSCAN_WORK                    104
#define IDC_IMG_EXAM_ANIMATION                  105
#define IDC_IMG_EXAM_RESULT_LEVEL               106
#define IDC_LBL_EXAM_RESULT_TEXT                107
#define IDC_DIV_EXAM_WORKING                    108
#define IDC_DIV_EXAM_FINISH                     109
#define IDC_PROGRESS_VIRSCAN_CLOUD              110
#define IDC_LIST_VIRUS                          111
#define IDC_PROGRESS_EXAM                       112
#define IDC_LBL_EXAM_RESTART                    113
#define IDC_IE_ONLINE_INFO                      114
#define IDC_LBL_VIRSCAN_CLOUD_STEP              115
#define IDC_LBL_VIRSCAN_SCANNED_FILE_COUNT      116
#define IDC_LBL_VIRSCAN_VIRUS_COUNT             117
#define IDC_LBL_VIRSCAN_SCANNED_TIME            118
#define IDC_DIV_EXAM_NOTICE_0                   119
#define IDC_DIV_EXAM_NOTICE_1                   120
#define IDC_IMG_EXAM_NOTICE_STAT_0              121
#define IDC_IMG_EXAM_NOTICE_STAT_1              122
#define IDC_LBL_EXAM_NOTICE_0                   123
#define IDC_LBL_EXAM_NOTICE_1                   124
#define IDC_BTN_EXAM_NAVIGATE_0                 125
#define IDC_BTN_EXAM_NAVIGATE_1                 126
#define IDC_DIV_VIRSCAN_SCANNING                127
#define IDC_DIV_VIRSCAN_SCAN_FINISH             128
#define IDC_BTN_VIRSCAN_PAUSE                   129
#define IDC_BTN_VIRSCAN_STOP                    130
#define IDC_BTN_VIRSCAN_RESUME                  131
#define IDC_BTN_VIRSCAN_CLEAN_ALL_VIRUS         132
#define IDC_BTN_VIRSCAN_SKIP_ALL_VIRUS          133
#define IDC_DIV_VIRSCAN_RESULT_NO_VIRUS         134
#define IDC_BTN_VIRSCAN_RESULT_NO_VIRUS_OK      135
#define IDC_TAB_MAIN                            136
#define IDC_BTN_MAIN_GO_VIRSCAN                 137
#define IDC_BTN_EXAM_STOP                       138
#define IDC_DIV_EXAM_RESULT_TEXT                139
#define IDC_IMG_VIRSCAN_CLOUD_ANIMATION         140
#define IDC_LBL_VIRSCAN_RESULT_NO_VIRUS_FILES   141
#define IDC_LBL_VIRSCAN_RESULT_NO_VIRUS_TIME    142
#define IDC_LBL_VIRSCAN_SCAN_FINISH_TITLE       143
#define IDC_TRV_FOLDER_BROWSE                   144
#define IDC_DIV_VIRSCAN_CLEANING                145
#define IDC_PROGRESS_VIRSCAN_CLEAN              146
#define IDC_DIV_VIRSCAN_NEED_CLEAN_BUTTONS      147
#define IDC_DIV_VIRSCAN_ALL_CLEAN_BUTTONS       148
#define IDC_DIV_VIRSCAN_REBOOT_BUTTONS          149
#define IDC_BTN_VIRSCAN_RETURN                  150
#define IDC_BTN_VIRSCAN_REBOOT_NOW              151
#define IDC_BTN_VIRSCAN_REBOOT_LATER            152
#define IDC_DIV_VIRSCAN_RESULT_VIRUS_REMAIN     153
#define IDC_DIV_VIRSCAN_RESULT_VIRUS_ALL_CLEAN  154
#define IDC_CHK_VIRSCAN_CHECK_ALL_VIRUS         155
#define IDC_BTN_VIRSCAN_RETURN_2                156
#define IDC_BTN_VIRSCAN_VIEW_REMAIN             157
#define IDC_BTN_VIRSCAN_RETURN_3                158
#define IDC_LBL_VIRSCAN_RESULT_NO_VIRUS_VIRUS   159
#define IDC_LBL_VIRSCAN_RESULT_ALL_CLEAN_FILES  160
#define IDC_LBL_VIRSCAN_RESULT_ALL_CLEAN_VIRUS  161
#define IDC_LBL_VIRSCAN_RESULT_ALL_CLEAN_TIME   162
#define IDC_LBL_VIRSCAN_RESULT_REMAIN_FILES     163
#define IDC_LBL_VIRSCAN_RESULT_REMAIN_VIRUS     164
#define IDC_LBL_VIRSCAN_RESULT_REMAIN_TIME      165
#define IDC_LBL_VIRSCAN_RESULT_REMAIN_REMAIN_VIRUS  166
#define IDC_LST_VIRSCAN_LOG                     167
#define IDC_LBL_VIRSCAN_SHOW_LOG                168
#define IDC_BTN_VIRSCAN_CLEAR_LOG               169
#define IDC_BTN_MAIN_GO_LEAKSCAN                170
#define IDC_BTN_MAIN_GO_FIX_IE                  171
#define IDC_BTN_MAIN_GO_PLUGINSCAN              172
#define IDC_BTN_MAIN_GO_FULL_VIRSCAN            173
#define IDC_LST_QUARANTINE                      174
#define IDC_LBL_SHOW_QUARANTINE                 175
#define IDC_LBL_VIRSCAN_CLOUD_SCAN_FILE_NAME    176
// #define IDC_BTN_QUARANTINE_REMOVE               177
// #define IDC_BTN_QUARANTINE_RETRIEVE             178
#define IDC_DIV_ECHO_NOFINISH                   179
#define IDC_DIV_ECHO_OK                         180
#define IDC_DIV_ECHO_CONNECT_ERROR              181
#define IDC_DIV_ECHO_CHECK_SELF_ERROR           182
#define IDC_LBL_PROTECTION_STATUS_LEAK          183
#define IDC_LBL_PROTECTION_STATUS_REGISTER      184
#define IDC_LBL_PROTECTION_STATUS_PROCESS       185
#define IDC_LBL_PROTECTION_STATUS_UDISK         186
#define IDC_LBL_PROTECTION_TURN_OFF_LEAK        187
#define IDC_LBL_PROTECTION_TURN_OFF_REGISTER    188
#define IDC_LBL_PROTECTION_TURN_OFF_PROCESS     189
#define IDC_LBL_PROTECTION_TURN_OFF_UDISK       190
#define IDC_LBL_PROTECTION_TURN_ON_LEAK         191
#define IDC_LBL_PROTECTION_TURN_ON_REGISTER     192
#define IDC_LBL_PROTECTION_TURN_ON_PROCESS      193
#define IDC_LBL_PROTECTION_TURN_ON_UDISK        194
#define IDC_RICH_VIRSCAN_LAST_SCAN_INFO         195
#define IDC_LBL_VIRSCAN_LAST_SCAN_TROJAN_COUNT  196
#define IDC_LBL_VIRSCAN_QUARANTINE_COUNT        197
#define IDC_DIV_VIRSCAN_LAST_SCAN               198
#define IDC_LBL_VIRSCAN_NOT_SCANNED             199
#define IDC_IMG_PROTECTION_STAT_LEAK            200
#define IDC_IMG_PROTECTION_STAT_REGISTER        201
#define IDC_IMG_PROTECTION_STAT_PROCESS         202
#define IDC_IMG_PROTECTION_STAT_UDISK           203
#define IDC_DIV_VIRSCAN_SCANNING_BUTTONS        204
#define IDC_DIV_VIRSCAN_DYNAMIC_NOTICE          205
#define IDC_LBL_TITLE_UPDATE                    206
#define IDC_LBL_TITLE_SETTING                   207
#define IDC_LBL_VIRSCAN_RESCAN_VIRUS            208
#define IDC_IE_VIRSCAN                          209
#define IDC_DIV_VIRSCAN_DYNAMIC_NOTICE_PARENT   210
#define IDC_DIV_VIRSCAN_RESULT_NEED_REBOOT      211
#define IDC_LBL_VIRSCAN_RESULT_REBOOT_FILES     212
#define IDC_LBL_VIRSCAN_RESULT_REBOOT_VIRUS     213
#define IDC_LBL_VIRSCAN_RESULT_REBOOT_REBOOT_VIRUS  214
#define IDC_LBL_VIRSCAN_RESULT_REBOOT_TIME      215
#define IDC_BTN_VIRSCAN_RESULT_REBOOT_NOW       216
#define IDC_BTN_VIRSCAN_RESULT_REBOOT_LATER     217
#define IDC_DIV_VIRSCAN_RESULT_NO_VIRUS_TODO_1  218
#define IDC_DIV_VIRSCAN_RESULT_NO_VIRUS_TODO_2  219
#define IDC_LBL_VIRSCAN_RESULT_NO_VIRUS_TODO_TEXT_1 220
#define IDC_LBL_VIRSCAN_RESULT_NO_VIRUS_TODO_TEXT_2 221
#define IDC_LBL_VIRSCAN_RESULT_NO_VIRUS_TODO_NAVIGATE_1 222
#define IDC_LBL_VIRSCAN_RESULT_NO_VIRUS_TODO_NAVIGATE_2 223
#define IDC_DIV_VIRSCAN_RESULT_ALL_CLEAN_TODO_1     224
#define IDC_DIV_VIRSCAN_RESULT_ALL_CLEAN_TODO_2     225
#define IDC_LBL_VIRSCAN_RESULT_ALL_CLEAN_TODO_TEXT_1    226
#define IDC_LBL_VIRSCAN_RESULT_ALL_CLEAN_TODO_TEXT_2    227
#define IDC_LBL_VIRSCAN_RESULT_ALL_CLEAN_TODO_NAVIGATE_1   228 
#define IDC_LBL_VIRSCAN_RESULT_ALL_CLEAN_TODO_NAVIGATE_2   229
#define IDC_LBL_VIRSCAN_REPORTED_LOG            230
#define IDC_LBL_VIRSCAN_SHOW_REPORT_LOG_DLG     231
#define IDC_LBL_PROTECTION_LOG_TIME_0           232
#define IDC_LBL_PROTECTION_LOG_TIME_1           233
#define IDC_LBL_PROTECTION_LOG_TIME_2           234
#define IDC_LBL_PROTECTION_LOG_TIME_3           235
#define IDC_LBL_PROTECTION_LOG_TIME_4           236
#define IDC_LBL_PROTECTION_LOG_TIME_5           237
#define IDC_LBL_PROTECTION_LOG_TIME_6           238
#define IDC_LBL_PROTECTION_LOG_TYPE_0           239
#define IDC_LBL_PROTECTION_LOG_TYPE_1           240
#define IDC_LBL_PROTECTION_LOG_TYPE_2           241
#define IDC_LBL_PROTECTION_LOG_TYPE_3           242
#define IDC_LBL_PROTECTION_LOG_TYPE_4           243
#define IDC_LBL_PROTECTION_LOG_TYPE_5           244
#define IDC_LBL_PROTECTION_LOG_TYPE_6           245
#define IDC_LBL_PROTECTION_LOG_OP_0             246
#define IDC_LBL_PROTECTION_LOG_OP_1             247
#define IDC_LBL_PROTECTION_LOG_OP_2             248
#define IDC_LBL_PROTECTION_LOG_OP_3             249
#define IDC_LBL_PROTECTION_LOG_OP_4             250
#define IDC_LBL_PROTECTION_LOG_OP_5             251
#define IDC_LBL_PROTECTION_LOG_OP_6             252
#define IDC_LBL_PROTECTION_LOG_SHOW             253
#define IDC_LBL_PRODUCT_VERSION                 254
#define IDC_LBL_PROTECTION_LOG_COUNT            255
#define IDC_DIV_UPLIVE_CHECKING                 256
#define IDC_DIV_UPLIVE_CHECK_NEED_UPDATE        257
#define IDC_DIV_UPLIVE_CHECK_ALREADY_NEW        258
#define IDC_DIV_UPLIVE_UPDATE                   259
#define IDC_DIV_UPLIVE_UPDATING                 260
#define IDC_PROGRESS_UPLIVE_UPDATING            261

#define IDC_LBL_PROTECTION_SETTING				262
#define IDC_LBL_PROTECTION_SCAN					263
#define IDC_LBL_PROTECTION_TRUN_ON_ALL			264
#define IDC_DIV_PROTECTION_OK					265
#define IDC_DIV_PROTECTION_WARNING1				266
#define IDC_DIV_PROTECTION_WARNING2				267
#define IDC_DIV_PROTECTION_WARNING3				268

#define IDC_TXT_PROTECTION_TURN_OFF_LEAK        269
#define IDC_TXT_PROTECTION_TURN_OFF_REGISTER    270
#define IDC_TXT_PROTECTION_TURN_OFF_PROCESS     271
#define IDC_TXT_PROTECTION_TURN_OFF_UDISK       272
#define IDC_TXT_PROTECTION_TURN_ON_LEAK         273
#define IDC_TXT_PROTECTION_TURN_ON_REGISTER     274
#define IDC_TXT_PROTECTION_TURN_ON_PROCESS      275
#define IDC_TXT_PROTECTION_TURN_ON_UDISK        276

#define IDC_DIV_SCAN_STATISTIC                  277
#define IDC_DIV_CLEAN_STATISTIC                 278
#define IDC_LBL_VIRCLEAN_VIRUS_COUNT            279
#define IDC_LBL_VIRCLEAN_CLEANED_VIRUS_COUNT    280
#define IDC_LBL_VIRCLEAN_REMAIN_VIRUS_COUNT     281
#define IDC_IMG_VIRSCAN_SCAN_FINISH_TITLE       282

#define IDC_DIV_VIRSCAN_TIP_1                   283
#define IDC_DIV_VIRSCAN_TIP_2                   284
#define IDC_DIV_VIRSCAN_TIP_3                   285
#define IDC_DIV_VIRSCAN_TIP_4                   286
#define IDC_DIV_VIRSCAN_TIP_5                   287
#define IDC_DIV_VIRSCAN_TIP_6                   288
#define IDC_DIV_VIRSCAN_TIP_TEXT_1              289

#define IDC_LBL_VIRSCAN_ECHO_FAILED             290

#define IDC_DIV_PROTECTION_LOG_TIP1				291
#define IDC_DIV_PROTECTION_LOG_TIP2				292


#define IDC_DIV_VIRSCAN_TIP_7                   302
#define IDC_LBL_VIRSCAN_TIP_REBOOT              303

#define IDC_TXT_PROTECTION_LEAK1				304
#define IDC_TXT_PROTECTION_LEAK2				305
#define IDC_TXT_PROTECTION_RISK1				306
#define IDC_TXT_PROTECTION_RISK2				307
#define IDC_TXT_PROTECTION_PROCESS1				308
#define IDC_TXT_PROTECTION_PROCESS2				309
#define IDC_TXT_PROTECTION_UDISK1				310
#define IDC_TXT_PROTECTION_UDISK2				311
#define IDC_IMG_PROTECTION_STATUS				312

#define IDC_DIV_VIRSCAN_AVENGINE_NOINSTALL      313
#define IDC_DIV_VIRSCAN_AVENGINE_INSTALLING     314
#define IDC_DIV_VIRSCAN_AVENGINE_INSTALLED      315
#define IDC_LBL_VIRSCAN_INSTALL_AVENGINE        316

#define IDC_LBL_VIRSCAN_SETTING_SHOW_SETTING_DLG 317
#define IDC_LBL_VIRSCAN_SETTING_AUTOCLEAN        318

#define IDC_IMG_VIRSCAN_AVE_ANIMATION           319
#define IDC_LBL_VIRSCAN_AVE_STEP                320
#define IDC_LBL_VIRSCAN_AVE_SCAN_FILE_NAME      321
#define IDC_PROGRESS_VIRSCAN_AVE                322
#define IDC_DIV_VIRSCAN_AVE_SCANNING            323
#define IDC_DIV_VIRSCAN_AVE_NOINSTALL           324
#define IDC_DIV_VIRSCAN_AVE_INSTALLING          325
#define IDC_DIV_VIRSCAN_AVE_INSTALLED           326
#define IDC_DIV_VIRSCAN_AVE_SCANNING_NOINSTALL  327

#define IDC_IMG_VIRSCAN_CLEAN_ANIMATION_1       328
#define IDC_IMG_VIRSCAN_CLEAN_ANIMATION_2       329
#define IDC_IMG_VIRSCAN_CLEAN_ANIMATION_3       330
#define IDC_LBL_VIRSCAN_CLEAN_FILE_NAME         331

#define IDC_LBL_AVE_SIGN_VERSION                332
#define IDC_DIV_APP_VERSION_INFO                333

#define IDC_BTN_UNKNOWN_LOG_KILL_ALL_VIRUS      334
#define IDC_LBL_VIRSCAN_SHOW_WHITELIST_DLG      335
#define IDC_LBL_VIRSCAN_WHITELIST_STATUS        336

#define IDC_LBL_ZHUANSHA_INFO_1                 337
#define IDC_LBL_ZHUANSHA_INFO_2                 338
#define IDC_LBL_VIRSCAN_WHITELIST_ADD           339
#define IDC_TXT_VIRSCAN_TRUST_PLUG_TIP			340

#define IDC_LST_PROTECTION_CTRL                 341
#define IDC_LBL_PROTECTION_CTRL_CHECK_ALL       342
#define IDC_LBL_PROTECTION_CTRL_UNCHECK_ALL     343
#define IDC_BTN_PROTECTION_CTRL_REMOVE_CHECK    344
#define IDC_LBL_PROTECTION_CTRL_COUNT           345
#define IDC_LST_PROTECTION_CTRL_LOG             346
#define IDC_DIV_PROTECTION_CTRL_LOG             347
#define IDC_BTN_PROTECTION_CTRL_LOG_CLEAR       348
#define IDC_TXT_PROTECTION_CTRL_CHECK           349

// 木马扫描白名单对话框独立控件ID
#define IDC_LST_LIST                            100
#define IDC_CHK_LIST_CHECK_ALL                  101
#define IDC_LBL_WHITELIST_ADD_FILE              102
#define IDC_LBL_WHITELIST_DEL_FILE              103

// 木马扫描报告对话框独立控件ID
#define IDC_IMG_VIRSCAN_REPORT_STATUS_ICON      100
#define IDC_DIV_VIRSCAN_REPORT_TITLE            101
#define IDC_LBL_VIRSCAN_REPORT_TILTE            102
#define IDC_LBL_VIRSCAN_REPORT_SCAN_TIME        103
#define IDC_LBL_VIRSCAN_REPORT_SCAN_FILE        104
#define IDC_LBL_VIRSCAN_REPORT_VIRUS            105
#define IDC_BTN_VIRSCAN_REPORT_UPLOAD_UNKNOWN   106
#define IDC_LBL_VIRSCAN_REPORT_UNKNOWN          107
#define IDC_BTN_VIRSCAN_REPORT_CLEAN_VIRUS      108
#define IDC_BTN_VIRSCAN_REPORT_SKIP_VIRUS       109
#define IDC_DIV_VIRSCAN_REPORT_SAFE_BUTTONS     110
#define IDC_DIV_VIRSCAN_REPORT_VIRUS_BUTTONS    111
#define IDC_LBL_VIRSCAN_REPORT_UPLOAD_UNKNOWN   112
#define IDC_DIV_VIRSCAN_REPORT_REBOOT_BUTTONS   113
#define IDC_LBL_VIRSCAN_REPORT_REBOOT_NOW       114
#define IDC_LBL_VIRSCAN_REPORT_REBOOT_LATER     115
#define IDC_LBL_VIRSCAN_REPORT_NOTICE_1         116
#define IDC_LBL_VIRSCAN_REPORT_NOTICE_2         117
#define IDC_DIV_VIRSCAN_REPORT_NOTICE           118

// 隔离对话框独立控件ID
#define IDC_CHK_QUARANTINE_CHECK_ALL            100
#define IDC_BTN_QUARANTINE_REMOVE               101
#define IDC_BTN_QUARANTINE_RETRIEVE             102
#define IDC_DIV_QUARANTINE_DESCRIPTION          103
#define IDC_DIV_QUARANTINE_PROGRESS             104

// 上报未知文件提示窗口独立控件ID

#define IDC_LBL_SHOW_UNKNOWN_FILES              100
#define IDC_CHK_JOIN_SKYLARK                    101
#define IDC_LST_UNKNOWN_FILES                   102

// 监控信任项列表控件ID

#define IDC_DIV_PROTCTRL_LISTITEM_BG            100
#define IDC_CHK_PROTCTRL_LISTITEM               101
#define IDC_ICO_PROTCTRL_LISTITEM_ICON          102
#define IDC_LBL_PROTCTRL_LISTITEM_FILENAME      103
#define IDC_LBL_PROTCTRL_LISTITEM_DETAIL        104
#define IDC_DIV_PROTCTRL_LISTITEM_TRUST         105
#define IDC_DIV_PROTCTRL_LISTITEM_DENY          106
#define IDC_BTN_PROTCTRL_LISTITEM_CANCEL_TRUST  107
#define IDC_BTN_PROTCTRL_LISTITEM_CANCEL_DENY   108

// 监控日志列表控件ID

#define IDC_LBL_PROTLOG_LISTITEM_TIME          100
#define IDC_LBL_PROTLOG_LISTITEM_TYPE          101
#define IDC_LBL_PROTLOG_LISTITEM_DETAIL        102
#define IDC_LBL_PROTLOG_LISTITEM_FILENAME      103
#define IDC_LBL_PROTLOG_LISTITEM_OP            104

// 设置窗口独立控件ID

#define IDC_TAB_SETTING                         100
#define IDC_CHK_SETTING_TRAY_AUTORUN            101
#define IDC_CHK_SETTING_TRAY_AUTOCHECK          102
#define IDC_CHK_SETTING_BKSAFE_AUTO_EXAM        103
#define IDC_CHK_SETTING_SVC_JOIN_BEIKECLOUD     104
#define IDC_CHK_SETTING_SVC_AUTO_CLEAN          108
#define IDC_CHK_SETTING_SVC_MANUAL_CLEAN        109
#define IDC_BTN_SETTING_SHOW_QUARANTINEDLG      110
#define IDC_TXT_SETTING_TRAY_AUTORUN_WARNING1	200 // 没开启警告
#define IDC_TXT_SETTING_TRAY_AUTORUN_WARNING2	201 // 开启后警告
#define IDC_LBL_SETTING_TRAY_PROTECTION_TRUN_ON	202
#define IDC_CHK_SETTING_TRAY_AUTO_UPDATE		203 // 自动升级
#define IDC_CHK_SETTING_TRAY_ASK_UPDATE		204 // 询问升级
#define IDC_CHK_SETTING_BKSAFE_DAY_EXAM			205 // 每天一次体检
#define IDC_CHK_SETTING_BKSAFE_MANUAL_EXAM		206 // 手动体检

#define IDC_LBL_SETTING_WHITE_LIST              207

// 
#define IDC_BTN_SETTING_VULFIX_SELFOLDER		112
#define IDC_BTN_SETTING_VULFIX_OPENFOLDER		113
#define IDC_BTN_SETTING_VULFIX_DELETEFILES	    115


#define IDC_CHK_SETTING_TRAY_GAMEBYPASS         116
#define IDC_CHK_SETTING_IEFIX_RIGHTMENU         117
#define IDC_CHK_SETTING_IEFIX_TOOLBARICON       118
#define IDC_CHK_SETTING_IEFIX_THIRDTOOLBAR      119
#define IDC_CHK_SETTING_IEFIX_BHO               120
#define IDC_CHK_SETTING_IEFIX_SAFEWEB           121
#define IDC_CHK_SETTING_IEFIX_PROTOCOL          122
#define IDC_CHK_SETTING_IEFIX_SEARCHENG         123

#define IDC_DIV_SETTING_VULFIX_SAVE_DIR			124
#define IDC_CHK_SETTING_VULFIX_NO_SAVE			125
#define IDC_CHK_SETTING_VULFIX_SAVE_DOWN		126

#define IDC_CHK_SETTING_TRAY_SAFEPASS           127

// 体检新UI使用到的控件ID，从500开始
#define IDC_EXAM_CTRL_ID_BEGIN					500
#define IDC_EXAM_LISTVIEW_ID					IDC_EXAM_CTRL_ID_BEGIN+1
#define IDC_EXAM_TXT_SETTING_ID					IDC_EXAM_CTRL_ID_BEGIN+2
#define IDC_EXAM_LNK_SETTING_ID					IDC_EXAM_CTRL_ID_BEGIN+3
#define IDC_EXAM_DLG_HISTORY					IDC_EXAM_CTRL_ID_BEGIN+4
#define IDC_EXAM_IMAG_DIY						IDC_EXAM_CTRL_ID_BEGIN+5
#define IDC_EXAM_IMAG_ENG						IDC_EXAM_CTRL_ID_BEGIN+6
#define IDC_EXAM_TXT_HISTORY					IDC_EXAM_CTRL_ID_BEGIN+7
#define IDC_EXAM_BTN_EXAM						IDC_EXAM_CTRL_ID_BEGIN+8
#define IDC_EXAM_DLG_DIY						IDC_EXAM_CTRL_ID_BEGIN+9
#define IDC_EXAM_LNK_SETTING_DIY_ID				IDC_EXAM_CTRL_ID_BEGIN+10
#define IDC_EXAM_LNK_TXT_SETTING_ID_2			IDC_EXAM_CTRL_ID_BEGIN+11
#define IDC_EXAM_IMAGE_TROJAN_HISTORY			IDC_EXAM_CTRL_ID_BEGIN+12
#define IDC_EXAM_EXAMTXT_DIY					IDC_EXAM_CTRL_ID_BEGIN+13
#define IDC_EXAM_SCANTROJAN_HISTORY				IDC_EXAM_CTRL_ID_BEGIN+14
#define IDC_EXAM_EXAMTXT_DLG_DIY				IDC_EXAM_CTRL_ID_BEGIN+15
#define IDC_EXAM_ENG_STATE						IDC_EXAM_CTRL_ID_BEGIN+16
#define IDC_EXAM_TXT_HISTORY_INFO				IDC_EXAM_CTRL_ID_BEGIN+17
#define IDC_EXAM_DLG_SETTINGID_1				IDC_EXAM_CTRL_ID_BEGIN+18
#define IDC_EXAM_DLG_SETTINGID_2				IDC_EXAM_CTRL_ID_BEGIN+19
#define IDC_EXAM_LNK_SETTIMGID_3				IDC_EXAM_CTRL_ID_BEGIN+20
#define IDC_EXAM_IMAG_STATUS					IDC_EXAM_CTRL_ID_BEGIN+21
#define IDC_EXAM_LNK_STARTENG_ID				IDC_EXAM_CTRL_ID_BEGIN+22
#define IDC_EXAM_DLG_ENG_ENABLE1_ID				IDC_EXAM_CTRL_ID_BEGIN+23//云引擎是否开启
#define IDC_EXAM_DLG_ENG_ENABLE2_ID				IDC_EXAM_CTRL_ID_BEGIN+24//云引擎是否安装
#define IDC_EXAM_DLG_ENG1_ID					IDC_EXAM_CTRL_ID_BEGIN+25//本地引擎是否开启
#define IDC_EXAM_DLG_ENG2_ID					IDC_EXAM_CTRL_ID_BEGIN+26//本地引擎是否安装
#define IDC_EXAM_DLG_ENG_OK_ID					IDC_EXAM_CTRL_ID_BEGIN+27//所有引擎都已经OK
#define IDC_EXAM_DLG_ENG_INIT_ID				IDC_EXAM_CTRL_ID_BEGIN+28//初始化引擎
#define IDC_EXAM_LNK_ENG_START1_ID				IDC_EXAM_CTRL_ID_BEGIN+29//开启云引擎
#define IDC_EXAM_LNK_ENG_FIX1_ID				IDC_EXAM_CTRL_ID_BEGIN+30//解决云引擎失败
#define IDC_EXAM_LNK_ENG_INSTALL_ID				IDC_EXAM_CTRL_ID_BEGIN+31//安装本地引擎
#define IDC_EXAM_LNK_ENG_START2_ID				IDC_EXAM_CTRL_ID_BEGIN+32//开启本地引擎
#define IDC_EXAM_DLG_30DAYS_ID					IDC_EXAM_CTRL_ID_BEGIN+33//30天没有进行扫描
#define IDC_EXAM_DLG_7DAYS_ID					IDC_EXAM_CTRL_ID_BEGIN+34//7天没有进行扫描
#define IDC_EXAM_DLG_SCANLOG_ID					IDC_EXAM_CTRL_ID_BEGIN+35//查杀日志
#define IDC_EXAM_DLG_UNKNOWNLOG_ID				IDC_EXAM_CTRL_ID_BEGIN+36//未知文件上报日志
#define IDC_EXAM_LNK_SHOWSCANLOG_ID				IDC_EXAM_CTRL_ID_BEGIN+37//查看查杀日志
#define IDC_EXAM_LNK_UNKNOWNLOG_ID				IDC_EXAM_CTRL_ID_BEGIN+38//查看未知文件日志
#define IDC_EXAM_DLG_SCANED_ID					IDC_EXAM_CTRL_ID_BEGIN+39//近期是否做过查杀
#define IDC_EXAM_DLG_DEFAULTLOG_ID				IDC_EXAM_CTRL_ID_BEGIN+40//默认日志显示文字
#define IDC_EXAM_LNK_SCANCOUNT_ID				IDC_EXAM_CTRL_ID_BEGIN+41
#define IDC_EXAM_LNK_UNKNOWNCOUNT_ID			IDC_EXAM_CTRL_ID_BEGIN+42
#define IDC_EXAM_DLG_EXAMSCAN_ID				IDC_EXAM_CTRL_ID_BEGIN+43//体检中发现木马
#define IDC_EXAM_DLG_INSTALLING_ID				IDC_EXAM_CTRL_ID_BEGIN+44
#define IDC_EXAM_LNK_STARTKILL1_ID				IDC_EXAM_CTRL_ID_BEGIN+45
#define IDC_EXAM_LNK_STARTKILL2_ID				IDC_EXAM_CTRL_ID_BEGIN+46
#define IDC_EXAM_LNK_STARTKILL3_ID				IDC_EXAM_CTRL_ID_BEGIN+47
#define IDC_EXAM_DLG_NOKILL_ID					IDC_EXAM_CTRL_ID_BEGIN+48
#define IDC_EXAM_LNK_STARTKILL4_ID				IDC_EXAM_CTRL_ID_BEGIN+49
#define IDC_EXAM_TEXT_REKILL_ID					IDC_EXAM_CTRL_ID_BEGIN+50
#define IDC_EXAM_ANTI_ID						IDC_EXAM_CTRL_ID_BEGIN+51
#define IDC_EXAM_LNK_STARTKILL5_ID				IDC_EXAM_CTRL_ID_BEGIN+52
#define IDC_EXAM_TEXT_FINDTROJAN_ID				IDC_EXAM_CTRL_ID_BEGIN+53
#define IDC_EXAM_DLG_NOTROJAN_ID				IDC_EXAM_CTRL_ID_BEGIN+54
#define IDC_EXAM_TEXT_NOTROJAN_ID				IDC_EXAM_CTRL_ID_BEGIN+55
#define IDC_EXAM_TEXT_SCAN_LOG_ID				IDC_EXAM_CTRL_ID_BEGIN+56//最近一次扫描
#define IDC_EXAM_LNK_STARTKILL6_ID				IDC_EXAM_CTRL_ID_BEGIN+57
#define IDC_EXAM_BTN_RETRAY_ID					IDC_EXAM_CTRL_ID_BEGIN+58//重试云引擎连接
#define IDC_EXAM_BTN_CLEAN_GBG_ID				IDC_EXAM_CTRL_ID_BEGIN+59//更新实时保护的状态
#define IDC_EXAM_BTN_MODIFY_SAFEMON_ID			IDC_EXAM_CTRL_ID_BEGIN+60//设置实时保护
#define IDC_EXAM_BTN_CLEAN_OP1_ID				IDC_EXAM_CTRL_ID_BEGIN+61//推荐操作1
#define IDC_EXAM_BTN_CLEAN_OP2_ID				IDC_EXAM_CTRL_ID_BEGIN+62//推荐操作2
#define IDC_EXAM_BTN_CLEAN_OP3_ID				IDC_EXAM_CTRL_ID_BEGIN+63//推荐操作3
#define IDC_EXAM_BTN_CLEAN_OP4_ID				IDC_EXAM_CTRL_ID_BEGIN+64//推荐操作4
#define IDC_EXAM_BTN_CLEAN_OP5_ID				IDC_EXAM_CTRL_ID_BEGIN+65//推荐操作4
#define IDC_EXAM_BTN_CLEAN_OP5TEXT_ID			IDC_EXAM_CTRL_ID_BEGIN+66//实时保护推荐文字
#define IDC_EXAM_CTRL_ID_END					IDC_EXAM_CTRL_ID_BEGIN+299

//体检界面中弹出的对话框的界面上的控件ID ，从800开始
#define IDC_EXAM_DLG_CTRL_ID_BEGIN				800
//shareresources
#define IDC_EXAM_DLG_SR_LISTVIEW_ID				IDC_EXAM_DLG_CTRL_ID_BEGIN+1//LISTVIEWID
#define IDC_EXAM_BTN_SR_CANCEL_ID				IDC_EXAM_DLG_CTRL_ID_BEGIN+2//取消共享
#define IDC_EXAM_BTN_SR_CLOSE_ID				IDC_EXAM_DLG_CTRL_ID_BEGIN+3//关闭
#define IDC_EXAM_LNK_SR_CHECKALL_ID				IDC_EXAM_DLG_CTRL_ID_BEGIN+4//全选
#define IDC_EXAM_LNK_SR_UNCHECKALL_ID			IDC_EXAM_DLG_CTRL_ID_BEGIN+5//全不选	
#define IDC_EXAM_BTN_SR_RCLOSE_ID				IDC_EXAM_DLG_CTRL_ID_BEGIN+6//右上角关闭按钮
#define IDC_EXAM_BTN_SR_BELIEVE_ID				IDC_EXAM_DLG_CTRL_ID_BEGIN+7//信任共享
#define IDC_EXAM_LNK_SR_SHOWMORE_ID				IDC_EXAM_DLG_CTRL_ID_BEGIN+8//显示更多
//hosts
#define IDC_EXAM_LNK_HOSTS_CHECKALL_ID			IDC_EXAM_DLG_CTRL_ID_BEGIN+10//全选
#define IDC_EXAM_LNK_HOSTS_UNCHECKALL_ID		IDC_EXAM_DLG_CTRL_ID_BEGIN+11//全不选
#define IDC_EXAM_BTN_HOSTS_BELIEVE_ID			IDC_EXAM_DLG_CTRL_ID_BEGIN+12//信任
#define IDC_EXAM_BTN_HOSTS_UNBELIEVE_ID			IDC_EXAM_DLG_CTRL_ID_BEGIN+13//屏蔽
#define IDC_EXAM_BTN_HOSTS_CLOSE_ID				IDC_EXAM_DLG_CTRL_ID_BEGIN+14//关闭
#define IDC_EXAM_BTN_HOSTS_RCLOSE_ID			IDC_EXAM_DLG_CTRL_ID_BEGIN+15
#define IDC_EXAM_LIST_HOSTS_ID					IDC_EXAM_DLG_CTRL_ID_BEGIN+16
//safemon
#define IDC_EXAM_BTN_SAFEMON_CLOSE_ID			IDC_EXAM_DLG_CTRL_ID_BEGIN+30//右上角关闭
#define IDC_EXAM_BTN_SAFEMON_OK_ID				IDC_EXAM_DLG_CTRL_ID_BEGIN+31
#define IDC_EXAM_LNK_SHOWMORE_ID				IDC_EXAM_DLG_CTRL_ID_BEGIN+32
#define IDC_EXAM_DLG_CTRL_ID_END				IDC_EXAM_CTRL_ID_BEGIN+199

// 插件扫描的Control ID		范围从1001-1999
#define IDC_DIV_PLUG_START						1001
#define IDC_DIV_PLUG_TOP_SCANNING				1002
#define IDC_DIV_PLUG_TOP_RESULT					1003
#define IDC_DIV_PLUG_MID_INIT					1004
#define IDC_DIV_PLUG_MID_STOP_RES				1005
#define IDC_DIV_PLUG_BOTTOM_RESULT				1007
#define IDC_DIV_PLUG_NO_FIND					1008
#define IDC_DIV_PLUG_SCANNING					1009
#define IDC_DIV_PLUG_TOP_REMOVING				1010
#define IDC_DIV_PLUG_TOP_RESULT_1				1011
#define IDC_DIV_PLUG_BOTTOM_RESULT_1			1012
#define IDC_DIV_PLUG_BTM_SCANNING				1013

#define IDC_BTN_PLUG_MID_SCAN					1101
#define IDC_BTN_PLUG_MID_RESCAN					1102
#define IDC_BTN_PLUG_BTM_CHECK_ALL				1103
#define IDC_BTN_PLUG_BTM_CHECK_DANGER			1104
#define IDC_BTN_PLUG_TOP_CLEAR_CHECK			1105
#define IDC_BTN_PLUG_TOP_RESCAN					1106
#define IDC_BTN_PLUG_TOP_STOP_SCAN				1107
#define IDC_BTN_PLUG_BTM_CLEAR_CHECK			1108
#define IDC_BTN_PLUG_BTM_CLEAR_RESCAN			1109

#define IDC_DIV_PLUG_NONE_0						1110
#define IDC_STAT_PLUG_NONE_0					1111
#define IDC_LBL_PLUG_NONE_0						1112
#define	IDC_BTN_PLUG_NONE_0						1113

#define IDC_DIV_PLUG_NONE_1						1114
#define IDC_STAT_PLUG_NONE_1					1115
#define IDC_LBL_PLUG_NONE_1						1116
#define	IDC_BTN_PLUG_NONE_1						1117
#define IDC_TAB_PLUG_TYPE						1118
	
#define IDC_TXT_PLUG_TOP_ALL_NUMBER				1201
#define IDC_TXT_PLUG_TOP_DANGER_NUMBER			1202
#define IDC_TXT_PLUG_SCAN_PROC_STR				1203
#define IDC_TXT_PLUG_NO_FIND_BACK_HP			1204
#define IDC_TXT_PLUG_FIND_VIEW_LOG				1205
#define IDC_TXT_PLUG_VIEW_LOG					1206
#define IDC_TXT_PLUG_STOP_TOP_TIPS				1207
#define IDC_TXT_PLUG_REMOVE_PROC_STR			1208
#define IDC_TXT_PLUG_FP_TIP_SCAN_OUT_TIME		1209
#define IDC_TXT_PLUG_FP_TIP_NO_CLEAR_DANGER		1210
#define IDC_TXT_PLUG_FP_TIP_LSCAN_TIME			1211
#define IDC_TXT_PLUG_FP_VIEW_HISTORY			1212
#define IDC_TXT_PLUG_UPLOAD_DATAIL				1213

#define IDC_RW_PLUG_LIST_RESULT					1301
#define IDC_RW_PLUG_IE_HOMEPAGE					1302
#define IDC_RW_PLUG_LIST_LOG					1303
#define IDC_RW_PLUG_RPTQQ_DESC					1304
#define IDC_RW_PLUG_RPTQQ_QQ					1305
#define IDC_RW_PLUG_RPTQQ_NAME					1306

#define IDC_PLUG_SCAN_IMAGE						1401
#define IDC_PLUG_REMOVE_IMAGE					1402

#define IDC_PLUG_PROGRESS_SCAN_BAR				1501
#define IDC_PLUG_PROGRESS_REMOVE_BAR			1502
#define IDC_PLUG_PROGRESS_UPLOAD_BAR			1503

#define IDC_PLUG_DETAIL_DLG_EDIT				1601
#define IDC_BTN_PLUG_DETAIL_DLG_EXIT			1602
#define IDC_BTN_PLUG_DATAIL_DLG_COPY			1603
#define IDC_BTN_PLUG_DATAIL_DLG_XCLOSE			1604
#define IDC_BTN_PLUG_UPLOAD_CLOSE				1605
#define IDC_BTN_PLUG_UPLOAD_CANCEL				1606
#define IDC_BTN_PLUG_UPLOAD_OK					1607
#define IDC_BTN_PLUG_LOG_CLEAR_ALL				1608
#define IDC_BTN_PLUG_LOG_RETURN					1609
#define IDC_BTN_PLUG_LOG_CLOSE					1610
#define IDC_BTN_PLUG_RPTQQ_CLOSE				1611
#define IDC_BTN_PLUG_RPTQQ_OK					1612
#define IDC_BTN_PLUG_RPTQQ_CANCEL				1613

#define IDC_TAB_TITLE_PLUG_ALL					1614
#define IDC_TAB_TITLE_PLUG_DANGER				1615
#define IDC_TAB_TITLE_PLUG_UNK					1616
#define IDC_TAB_TITLE_PLUG_SAFE					1617
#define IDC_DIV_PLUG_SCAN_TOP_RES_DANGER		1618
#define IDC_DIV_PLUG_SCAN_TOP_RES_UNKNOWN		1619
#define IDC_DIV_PLUG_SCAN_TOP_RES_SAFE			1620
#define IDC_BTN_PLUG_NO_PLUG_RESCAN				1621
#define IDC_DIV_PLUG_SCAN_TOP_RES_CANCEL		1622

#define IDC_TXT_PLUG_SCAN_RES_NUM_DANGER_ALL	1623
#define IDC_TXT_PLUG_SCAN_RES_NUM_DANGER_DAN	1624
#define IDC_TXT_PLUG_SCAN_RES_NUM_UNK_ALL		1625
#define IDC_TXT_PLUG_SCAN_RES_NUM_UNK_UNK		1626
#define IDC_TXT_PLUG_SCAN_RES_NUM_SAFE_ALL		1627

#define IDC_DIV_PLUG_MID_NO_DANGER				1628
#define IDC_DIV_PLUG_MID_NO_UNK					1629
#define IDC_DIV_PLUG_MID_NO_SAFE				1630

#define IDC_TXT_PLUG_TOP_DANGER_RESCAN			1631
#define IDC_TXT_PLUG_TOP_UNK_RESCAN				1632
#define IDC_TXT_BTM_RESCAN						1633
#define IDC_TXT_PLUG_TOP_NOPLUG_RESCAN			1634
#define IDC_TXT_PLUG_TOP_CANCEL_RESCAN			1635
#define IDC_TXT_PLUG_DETAIL_NAME				1636
	

//define IEFixEng 3000-3999 add by zbl
#define IDC_IEFIX_CTRL_ID_BEGIN						3000
#define IDC_IEFIX_BTN_IEFIX							IDC_IEFIX_CTRL_ID_BEGIN+1
#define IDC_IEFIX_BTN_IESET							IDC_IEFIX_CTRL_ID_BEGIN+2
#define IDC_IEFIX_BTN_IECLEAN						IDC_IEFIX_CTRL_ID_BEGIN+3
#define IDC_IEFIX_LISTVIEW_ID						IDC_IEFIX_CTRL_ID_BEGIN+4//LDListViewCtrl
#define IDC_IEFIX_DLG_IEFIX_1                       IDC_IEFIX_CTRL_ID_BEGIN+5//IE修复，简单界面，没有列出详细信息
#define IDC_IEFIX_DLG_LEFT_TAB						IDC_IEFIX_CTRL_ID_BEGIN+6//IE修复的左侧，里面包含几个按钮,IE修复，IE设置,IE清理
#define IDC_IEFIX_DLG_WORKAREA						IDC_IEFIX_CTRL_ID_BEGIN+7//IE修复中的整个右侧的工作区域
#define IDC_IEFIX_DLG_WORKAREA_FIX_1                IDC_IEFIX_CTRL_ID_BEGIN+8//IE修复中的工作区域的，一键修复
#define IDC_IEFIX_TEXT_LNK_SHOWALLITEM				IDC_IEFIX_CTRL_ID_BEGIN+9//查看更多修复项目
#define IDC_IEFIX_BTN_FIX_1							IDC_IEFIX_CTRL_ID_BEGIN+10//一键修复
#define IDC_IEFIX_TEXT_LNK_SELECTALL				IDC_IEFIX_CTRL_ID_BEGIN+11//选中所有修复项目
#define IDC_IEFIX_TEXT_LNK_NOT_SELECTALL			IDC_IEFIX_CTRL_ID_BEGIN+12//取消全选
#define IDC_IEFIX_DLG_WORKAREA_BOTTOM				IDC_IEFIX_CTRL_ID_BEGIN+13//工作区域的底部
#define IDC_IEFIX_TAB								IDC_IEFIX_CTRL_ID_BEGIN+14//TAB窗口
#define IDC_IEFIX_DLG_TAB							IDC_IEFIX_CTRL_ID_BEGIN+15//TAB的DGL
#define IDC_IEFIX_LISTVIEW_CLEAN_ID					IDC_IEFIX_CTRL_ID_BEGIN+16//清理TAB下的LISTVIEW ID
#define IDC_IEFIX_BTN_CLEAN_1						IDC_IEFIX_CTRL_ID_BEGIN+17//一键清理功能,IE清理中的精简页面
#define IDC_IEFIX_TEX_LNK_SHOWALLITEM_CLEAN         IDC_IEFIX_CTRL_ID_BEGIN+18//查看所有清理项目
#define IDC_IEFIX_DLG_IECLEAN						IDC_IEFIX_CTRL_ID_BEGIN+19//IE清理的精简界面
#define IDC_IEFIX_TXT_LNK_PANEL						IDC_IEFIX_CTRL_ID_BEGIN+20//分割线/
#define IDC_IEFIX_BTN_FIX_2							IDC_IEFIX_CTRL_ID_BEGIN+21//修复页面中复杂页面中的一键修复
#define IDC_IEFIX_CHECKBOX_IEFIX					IDC_IEFIX_CTRL_ID_BEGIN+22//记住本次选中的项 ieFIX
#define IDC_IEFIX_DLG_IECLEAN_BOTTOM				IDC_IEFIX_CTRL_ID_BEGIN+23//IE清理的地步
#define IDC_IEFIX_TXT_LNK_SELALL_IECLEAN			IDC_IEFIX_CTRL_ID_BEGIN+24//IE清理中的全选
#define IDC_IEFIX_TXT_LNK_UNSELALL_IECLEAN			IDC_IEFIX_CTRL_ID_BEGIN+25//IE清理中的全取消
#define IDC_IEFIX_TXT_LNK_EXPAND_ALL_IECLEAN		IDC_IEFIX_CTRL_ID_BEGIN+26//IE清理中展开所有
#define IDC_IEFIX_TXT_LNK_NOT_EXPAND_ALL_IECLEAN    IDC_IEFIX_CTRL_ID_BEGIN+27//IE清理中部展开所有
#define IDC_IEFIX_DLG_IEFIX_SETTING					IDC_IEFIX_CTRL_ID_BEGIN+28//IE设置
#define IDC_IEFIX_EDIT_IEHOMEPAGE					IDC_IEFIX_CTRL_ID_BEGIN+29//IE首页设置
#define IDC_IEFIX_EDIT_IETITLE						IDC_IEFIX_CTRL_ID_BEGIN+30//IE标题设置
#define IDC_IEFIX_TXT_LNK_SET_BANK_HOMPAGE			IDC_IEFIX_CTRL_ID_BEGIN+31//IE空白页面
#define IDC_IEFIX_TXT_LNK_SET_IE_TITLE				IDC_IEFIX_CTRL_ID_BEGIN+32//IE标题
#define IDC_IEFIX_TXT_LNK_SET_BEIKE_HOMPAGE			IDC_IEFIX_CTRL_ID_BEGIN+33//IE贝壳导航页面
#define IDC_IEFIX_COMBOX_SEARCH_ENG					IDC_IEFIX_CTRL_ID_BEGIN+34//默认搜索引擎
#define IDC_IEFIX_COMBOX_HTMLEDIT					IDC_IEFIX_CTRL_ID_BEGIN+35//HTML编辑器
#define IDC_IEFIX_COMBOX_IEWNDSIZE					IDC_IEFIX_CTRL_ID_BEGIN+36//IE初始化窗口大小
#define IDC_IEFIX_COMBOX_IEWNDPOS					IDC_IEFIX_CTRL_ID_BEGIN+37//IE初始化窗口位置
#define IDC_IEFIX_COMBOX_IEMAXCONNECT				IDC_IEFIX_CTRL_ID_BEGIN+38//IE最大连接数
#define IDC_IEFIX_EDIT_IEDOWNLOADPATH				IDC_IEFIX_CTRL_ID_BEGIN+39//IE 下载目录
#define IDC_IEFIX_EDIT_IECACHEPATH					IDC_IEFIX_CTRL_ID_BEGIN+40//IE CACHE目录
#define IDC_IEFIX_EDIT_IEFAVORITES					IDC_IEFIX_CTRL_ID_BEGIN+41//IE收藏夹目录
#define IDC_IEFIX_TXT_LNK_SELECTPATH_DOWN			IDC_IEFIX_CTRL_ID_BEGIN+42//选择下载目录
#define IDC_IEFIX_TXT_LNK_SELECTPATH_CACHE			IDC_IEFIX_CTRL_ID_BEGIN+43//选择CACHE目录
#define IDC_IEFIX_TXT_LNK_SELECTPATH_FAVORITES		IDC_IEFIX_CTRL_ID_BEGIN+44//选择收藏夹目录
#define IDC_IEFIX_BTN_CLEAN_2						IDC_IEFIX_CTRL_ID_BEGIN+45//一键清理功能,IE清理中的显示详情页面 
#define IDC_IEFIX_CHECKBOX_IECLEAN					IDC_IEFIX_CTRL_ID_BEGIN+46//IE清理中记住所选中的项
#define IDC_IEFIX_BTN_IESET_UPDATE					IDC_IEFIX_CTRL_ID_BEGIN+47//立即生效
#define IDC_IEFIX_CHECKBOX_IETITOLE					IDC_IEFIX_CTRL_ID_BEGIN+48//IE标题
#define IDC_IEFIX_CHECKBOX_SEARCH					IDC_IEFIX_CTRL_ID_BEGIN+49//搜索引擎
#define IDC_IEFIX_CHECKBOX_VIEWCODE					IDC_IEFIX_CTRL_ID_BEGIN+50//源码查看工具
#define IDC_IEFIX_CHECKBOX_IESIZE					IDC_IEFIX_CTRL_ID_BEGIN+51//IE窗口大小
#define IDC_IEFIX_CHECKBOX_IEPOS					IDC_IEFIX_CTRL_ID_BEGIN+52//IE窗口位置
#define IDC_IEFIX_CHECKBOX_DOWN						IDC_IEFIX_CTRL_ID_BEGIN+53//下载目录
#define IDC_IEFIX_CHECKBOX_CACHE					IDC_IEFIX_CTRL_ID_BEGIN+54//缓存目录
#define IDC_IEFIX_CHECKBOX_FAVORITES				IDC_IEFIX_CTRL_ID_BEGIN+55//收藏夹目录
#define IDC_IEFIX_CHECKBOX_CONNECT					IDC_IEFIX_CTRL_ID_BEGIN+56//最大连接数
#define IDC_IEFIX_CHECKBOX_IEHOMPAGE				IDC_IEFIX_CTRL_ID_BEGIN+57//首页
#define IDC_IEFIX_EDIT_VIEWCODE						IDC_IEFIX_CTRL_ID_BEGIN+58//查看源文件
#define IDC_IEFIX_TXT_LNK_SELECTTOOL				IDC_IEFIX_CTRL_ID_BEGIN+59//选中源码查看工具
#define IDC_IEFIX_TXT_LNK_SET_SELALL				IDC_IEFIX_CTRL_ID_BEGIN+60//设置窗口全选
#define IDC_IEFIX_TXT_LNK_SET_UNSELALL				IDC_IEFIX_CTRL_ID_BEGIN+61//设置窗口取消全选
#define IDC_IEFIX_TXT_LNK_SET_DEFAULT				IDC_IEFIX_CTRL_ID_BEGIN+62//使用IE默认设置
#define IDC_IEFIX_TXT_LNK_IMPORT_SET				IDC_IEFIX_CTRL_ID_BEGIN+63//导入自定义设置
#define IDC_IEFIX_TXT_LNK_SAVE_SET					IDC_IEFIX_CTRL_ID_BEGIN+64//保存设置
#define IDC_IEFIX_DLG_LEFT_BK						IDC_IEFIX_CTRL_ID_BEGIN+65//整个左侧的背景窗口
#define IDC_IEFIX_TXT_LNK_SETTITLE					IDC_IEFIX_CTRL_ID_BEGIN+66//IE设置里面的“修改IE常用设置，使其更符合自己的需要”
#define IDC_IEFIX_DLG_IESET_BOTTOM					IDC_IEFIX_CTRL_ID_BEGIN+67//IE这之中真个底部的DLG
#define IDC_IEFIX_DLG_IEFIX_SHOWALL_LIST	        IDC_IEFIX_CTRL_ID_BEGIN+68//IE修复页面中的显示所有页面中的中间PANEL框框
#define IDC_IEFIX_TXT_LNK_FIX_TITLE					IDC_IEFIX_CTRL_ID_BEGIN+69//“一键修复”使用贝壳安全智能分析技术，自动识别 IE 被篡改的项目并智能修复。 
#define IDC_IEFIX_TXT_LNK_FIX_BACK					IDC_IEFIX_CTRL_ID_BEGIN+70//简洁模式>>
#define IDC_IEFIX_WORKAREA_IEFIX					IDC_IEFIX_CTRL_ID_BEGIN+71//IE修复页面的整个的右侧区域,不包括底栏
#define IDC_IEFIX_WORKAREA_IESET					IDC_IEFIX_CTRL_ID_BEGIN+72//IE设置页面的整个右侧区域，不包括底栏
#define IDC_IEFIX_LEFT_TAB							IDC_IEFIX_CTRL_ID_BEGIN+73//IE修复左侧的TAB
#define IDC_IEFIX_FIX_LIST_ID						IDC_IEFIX_CTRL_ID_BEGIN+74//IE修复页面中的修复状态列表
#define IDC_IEFIX_DLG_FIX							IDC_IEFIX_CTRL_ID_BEGIN+75//IE修复页面的对应的DLG
#define IDC_IEFIX_DLG_FIXLIST_BOTTOM				IDC_IEFIX_CTRL_ID_BEGIN+76//IE修复状态显示的额列表的底栏
#define IDC_IEFIX_SCAN_IMAGE						IDC_IEFIX_CTRL_ID_BEGIN+77//扫描进度窗口左侧的动画
#define IDC_IEFIX_PROGRESS_ID						IDC_IEFIX_CTRL_ID_BEGIN+78//扫描进度条
#define IDC_IEFIX_IEFIX_LIST_PANEL					IDC_IEFIX_CTRL_ID_BEGIN+79//
#define IDC_IEFIX_DLG_IEFIX_LIST					IDC_IEFIX_CTRL_ID_BEGIN+80//IE修复页面的顶栏
#define IDC_IEFIX_IMAG_SAFE_ID						IDC_IEFIX_CTRL_ID_BEGIN+81//IE修复过程中如果扫描是安全的时候显示的图片
#define IDC_IEFIX_IMAG_UNSAFE_ID					IDC_IEFIX_CTRL_ID_BEGIN+82//危险图片
#define IDC_IEFXI_RESULT_TXT_ID						IDC_IEFIX_CTRL_ID_BEGIN+83//显示扫描结果的文字
#define IDC_IEFIX_BTN_FIXLIST_ID					IDC_IEFIX_CTRL_ID_BEGIN+84//IE修复列表底部的暂停修复费
#define IDC_IEFIX_BTN_REBOOT_ID						IDC_IEFIX_CTRL_ID_BEGIN+85//立即重启
#define IDC_IEFIX_BTN_REBOOT_LATER_ID				IDC_IEFIX_CTRL_ID_BEGIN+86//稍后重启
#define IDC_IEFIX_BTN_GOBACK_ID						IDC_IEFIX_CTRL_ID_BEGIN+87//返回
#define IDC_IEFIX_BOTTOM_TXT_HOTFIX_ID				IDC_IEFIX_CTRL_ID_BEGIN+88//修复列表底部的显示
#define IDC_IEFIX_BOTTOM_TXT_LNK2_ID				IDC_IEFIX_CTRL_ID_BEGIN+89//修复列表底部的显示
#define IDC_IEFIX_DLG_HOTFIX_LNK_ID					IDC_IEFIX_CTRL_ID_BEGIN+90//推荐进行漏洞扫描 dlg
#define IDC_IEFIX_DLG_TROJAN_LNK_ID					IDC_IEFIX_CTRL_ID_BEGIN+91//推荐进行木马扫描 dlg
#define IDC_IEFIX_TROJIAN_TXT_LNK_ID				IDC_IEFIX_CTRL_ID_BEGIN+92//推荐进行木马全盘木马
#define IDC_IEFIX_DLG_REBOOT_LNK_ID					IDC_IEFIX_CTRL_ID_BEGIN+93//需要重新启动时进行提示 dlg
#define IDC_IEFIX_LISTVIEW_FIXLIST_ID				IDC_IEFIX_CTRL_ID_BEGIN+94//IE修复显示列表
#define IDC_IEFIX_DLG_PLUG_LNK_ID					IDC_IEFIX_CTRL_ID_BEGIN+95//提示进行插件扫描的窗口
#define IDC_IEFIX_PLUGFIX_TXT_LNK_ID				IDC_IEFIX_CTRL_ID_BEGIN+96//调用插件扫描的文字链接
#define IDC_IEFIX_DLG_PANEL_IEFIX_ID				IDC_IEFIX_CTRL_ID_BEGIN+97
#define IDC_IEFIX_CLEAN_DLG_NODATA_ID				IDC_IEFIX_CTRL_ID_BEGIN+98//IE清理是没有发现数据就显示这个
#define IDC_IEFIX_SCAN_INFO_TXT_LNK_ID				IDC_IEFIX_CTRL_ID_BEGIN+99//IE修复重，显示的扫描信息
#define IDC_IEFIX_SCAN_TITLE_TXT_ID					IDC_IEFIX_CTRL_ID_BEGIN+100
#define IDC_IEFIX_SCAN_TITLE_TXT_ID_1				IDC_IEFIX_CTRL_ID_BEGIN+101
#define IDC_IEFIX_SCAN_TITLE_TXT_ID_2				IDC_IEFIX_CTRL_ID_BEGIN+102
#define IDC_IEFIX_SCAN_TITLE_TXT_ID_3				IDC_IEFIX_CTRL_ID_BEGIN+103
#define IDC_IEFIX_SCAN_TITLE_TXT_ID_4				IDC_IEFIX_CTRL_ID_BEGIN+104
#define IDC_IEFIX_SCAN_TITLE_TXT_ID_5				IDC_IEFIX_CTRL_ID_BEGIN+105
#define IDC_IEFIX_SCAN_TITLE_TXT_ID_6				IDC_IEFIX_CTRL_ID_BEGIN+106
#define IDC_IEFIX_SCAN_TITLE_TXT_ID_7				IDC_IEFIX_CTRL_ID_BEGIN+107
#define IDC_IEFIX_CLEAN_SAFEDATA					IDC_IEFIX_CTRL_ID_BEGIN+108//
#define IDC_IEFIX_CLEAN_SAFEDATA_1					IDC_IEFIX_CTRL_ID_BEGIN+109
#define IDC_IEFIX_CLEAN_SAFEDATA_2					IDC_IEFIX_CTRL_ID_BEGIN+110
#define IDC_IEFIX_CLEAN_SAFEDATA_3					IDC_IEFIX_CTRL_ID_BEGIN+111
#define IDC_IEFIX_CLEAN_SAFEDATA_4					IDC_IEFIX_CTRL_ID_BEGIN+112
#define IDC_IEFIX_CLEAN_SAFEDATA_5					IDC_IEFIX_CTRL_ID_BEGIN+113
#define IDC_IEFIX_CLEAN_SAFEDATA_SHOW				IDC_IEFIX_CTRL_ID_BEGIN+114///
#define IDC_IEFIX_CLEAN_SAFEDATA_SHOW_1				IDC_IEFIX_CTRL_ID_BEGIN+115
#define IDC_IEFIX_CLEAN_SAFEDATA_SHOW_2				IDC_IEFIX_CTRL_ID_BEGIN+116
#define IDC_IEFIX_CLEAN_SAFEDATA_SHOW_3				IDC_IEFIX_CTRL_ID_BEGIN+117
#define IDC_IEFIX_CLEAN_SAFEDATA_SHOW_4				IDC_IEFIX_CTRL_ID_BEGIN+118
#define IDC_IEFIX_CLEAN_SAFEDATA_SHOW_5				IDC_IEFIX_CTRL_ID_BEGIN+119
#define IDC_IEFIX_FIX_TOTAL_TXT						IDC_IEFIX_CTRL_ID_BEGIN+120
#define IDC_IEFIX_DLG_FIX_RESULT					IDC_IEFIX_CTRL_ID_BEGIN+121
#define IDC_IEFIX_FIX_RESULT_FIXCOUNT				IDC_IEFIX_CTRL_ID_BEGIN+122
#define IDC_IEFIX_FIX_RESULT_IGNORECOUNT			IDC_IEFIX_CTRL_ID_BEGIN+123
#define IDC_IEFIX_FIX_ANTI_BG_ID					IDC_IEFIX_CTRL_ID_BEGIN+124
#define IDC_IEFIX_LOADDATA_PROGRESS_ID				IDC_IEFIX_CTRL_ID_BEGIN+125
#define IDC_IEFIX_BROWSER_PROTECT_DLG_BODY		    IDC_IEFIX_CTRL_ID_BEGIN+126   ///> 浏览器保护 对话框id
#define IDC_IEFIX_BROWSER_PROTECT_TAB_ID	        IDC_IEFIX_CTRL_ID_BEGIN+127   ///> 浏览器保护 tab
#define IDC_IEFIX_BROWSER_PROTECT_TAB_STATUS_ID		IDC_IEFIX_CTRL_ID_BEGIN+128   ///> 浏览器保护 保护状态
#define IDC_IEFIX_BROWSER_PROTECT_TAB_HISTORY_ID	IDC_IEFIX_CTRL_ID_BEGIN+129   ///> 浏览器保护 查看历史
#define IDC_IEFIX_BWSP_STATUS_TXT_TITLE	            IDC_IEFIX_CTRL_ID_BEGIN+130   ///> 浏览器保护 保护状态 标题
#define IDC_IEFIX_BWSP_STATUS_TXT_BLOCK_COUNT       IDC_IEFIX_CTRL_ID_BEGIN+131   ///> 浏览器保护 保护状态 拦截次数
#define IDC_IEFIX_BWSP_STATUS_LINK_HISTORY          IDC_IEFIX_CTRL_ID_BEGIN+132   ///> 浏览器保护 保护状态 查看历史
#define IDC_IEFIX_BWSP_STATUS_WEBPAGE_ICON          IDC_IEFIX_CTRL_ID_BEGIN+133   ///> 浏览器保护 保护状态 网页防护 图标
#define IDC_IEFIX_BWSP_STATUS_WEBPAGE_TITLE         IDC_IEFIX_CTRL_ID_BEGIN+134   ///> 浏览器保护 保护状态 网页防护 标题
#define IDC_IEFIX_BWSP_STATUS_WEBPAGE_DESCRIBE      IDC_IEFIX_CTRL_ID_BEGIN+135   ///> 浏览器保护 保护状态 网页防护 说明
#define IDC_IEFIX_BWSP_STATUS_WEBPAGE_OPENED        IDC_IEFIX_CTRL_ID_BEGIN+136   ///> 浏览器保护 保护状态 网页防护 已开启
#define IDC_IEFIX_BWSP_STATUS_WEBPAGE_CLOSED        IDC_IEFIX_CTRL_ID_BEGIN+137   ///> 浏览器保护 保护状态 网页防护 已关闭
#define IDC_IEFIX_BWSP_STATUS_WEBPAGE_CLOSE         IDC_IEFIX_CTRL_ID_BEGIN+138   ///> 浏览器保护 保护状态 网页防护 关闭
#define IDC_IEFIX_BWSP_STATUS_WEBPAGE_OPEN          IDC_IEFIX_CTRL_ID_BEGIN+139   ///> 浏览器保护 保护状态 网页防护 开启
#define IDC_IEFIX_BWSP_STATUS_URL_BLOCK_ICON        IDC_IEFIX_CTRL_ID_BEGIN+140   ///> 浏览器保护 保护状态 恶意网址拦截 图标
#define IDC_IEFIX_BWSP_STATUS_URL_BLOCK_TITLE       IDC_IEFIX_CTRL_ID_BEGIN+141   ///> 浏览器保护 保护状态 恶意网址拦截 标题
#define IDC_IEFIX_BWSP_STATUS_URL_BLOCK_DESCRIBE    IDC_IEFIX_CTRL_ID_BEGIN+142   ///> 浏览器保护 保护状态 恶意网址拦截 说明
#define IDC_IEFIX_BWSP_STATUS_URL_BLOCK_OPENED      IDC_IEFIX_CTRL_ID_BEGIN+143   ///> 浏览器保护 保护状态 恶意网址拦截 已开启
#define IDC_IEFIX_BWSP_STATUS_URL_BLOCK_CLOSED      IDC_IEFIX_CTRL_ID_BEGIN+144   ///> 浏览器保护 保护状态 恶意网址拦截 已关闭
#define IDC_IEFIX_BWSP_STATUS_URL_BLOCK_CLOSE       IDC_IEFIX_CTRL_ID_BEGIN+145   ///> 浏览器保护 保护状态 恶意网址拦截 关闭
#define IDC_IEFIX_BWSP_STATUS_URL_BLOCK_OPEN        IDC_IEFIX_CTRL_ID_BEGIN+146   ///> 浏览器保护 保护状态 恶意网址拦截 开启
#define IDC_IEFIX_BROWSER_PROTECT_TAB_PROCESS_ID	IDC_IEFIX_CTRL_ID_BEGIN+147   ///> 浏览器保护 信任/阻止程序
#define IDC_IEFIX_BROWSER_PROTECT_TAB_URL_ID    	IDC_IEFIX_CTRL_ID_BEGIN+148   ///> 浏览器保护 阻止网站
#define IDC_IEFIX_BWSP_TAB_STATUS_FOOTER_ID    	    IDC_IEFIX_CTRL_ID_BEGIN+149   ///> 浏览器保护 保护状态底栏
#define IDC_IEFIX_BWSP_TAB_PROCESS_FOOTER_ID        IDC_IEFIX_CTRL_ID_BEGIN+150   ///> 浏览器保护 信任/阻止底栏
#define IDC_IEFIX_BWSP_TAB_URL_FOOTER_ID    	    IDC_IEFIX_CTRL_ID_BEGIN+151   ///> 浏览器保护 阻止网站底栏
#define IDC_IEFIX_BWSP_TAB_HISTORY_FOOTER_ID        IDC_IEFIX_CTRL_ID_BEGIN+152   ///> 浏览器保护 查看历史底栏
#define IDC_IEFIX_BWSP_TAB_PROCESS_DEL_BTN          IDC_IEFIX_CTRL_ID_BEGIN+153   ///> 浏览器保护 信任/阻止底栏 删除按钮
#define IDC_IEFIX_BWSP_TAB_URL_CHECK_ALL            IDC_IEFIX_CTRL_ID_BEGIN+154   ///> 浏览器保护 阻止网站 全选
#define IDC_IEFIX_BWSP_TAB_URL_CHECK_SEPARATOR      IDC_IEFIX_CTRL_ID_BEGIN+155   ///> 浏览器保护 阻止网站 /
#define IDC_IEFIX_BWSP_TAB_URL_CHECK_ALL_NOT        IDC_IEFIX_CTRL_ID_BEGIN+156   ///> 浏览器保护 阻止网站 全不选
#define IDC_IEFIX_BWSP_TAB_URL_ADD                  IDC_IEFIX_CTRL_ID_BEGIN+157   ///> 浏览器保护 阻止网站 添加网站
#define IDC_IEFIX_BWSP_TAB_URL_DEL                  IDC_IEFIX_CTRL_ID_BEGIN+158   ///> 浏览器保护 阻止网站 删除
#define IDC_IEFIX_BWSP_TAB_HISTORY_CLEAR_ALL        IDC_IEFIX_CTRL_ID_BEGIN+159   ///> 浏览器保护 查看历史 清空历史
#define IDC_IEFIX_BWSP_TAB_DECRIBE_TXT              IDC_IEFIX_CTRL_ID_BEGIN+160   ///> 浏览器保护 各tab说明标题
#define IDC_IEFIX_BWSP_TAB_STATUS_LINK_MORE         IDC_IEFIX_CTRL_ID_BEGIN+161   ///> 浏览器保护 保护状态  了解详情
#define IDC_IEFIX_BWSP_TAB_STATUS_LINK_FAQ          IDC_IEFIX_CTRL_ID_BEGIN+162   ///> 浏览器保护 保护状态  常见问题
#define IDC_IEFIX_BWSP_TAB_STATUS_LINK_FAQ_MORE     IDC_IEFIX_CTRL_ID_BEGIN+163   ///> 浏览器保护 保护状态  了解详情 常见问题之间的"|"
#define IDC_IEFIX_BWSP_TAB_STATUS_LINK_REPORT       IDC_IEFIX_CTRL_ID_BEGIN+164   ///> 浏览器保护 保护状态  举报恶意网址
#define IDC_IEFIX_BWSP_TAB_STATUS_LINK_TEST  	    IDC_IEFIX_CTRL_ID_BEGIN+165   ///> 浏览器保护 保护状态  测试拦截效果
#define IDC_IEFIX_BWSP_TAB_STATUS_LINK_TEST_REPORT  IDC_IEFIX_CTRL_ID_BEGIN+166   ///> 浏览器保护 保护状态  了解详情 常见问题之间的"|"
#define IDC_IEFIX_CTRL_ID_ENG						IDC_IEFIX_CTRL_ID_BEGIN+999

// 漏洞修复是独立的对话框，所以Control ID可以与主对话框重复
#define IDC_DIV_VULFIX_DISPLAY                  100
#define IDC_DIV_VULFIX_SCANNING                 101
#define IDC_DIV_VULFIX_REPAIRING                102
#define IDC_PROGRESS_VULFIX_SCANNING            1000
#define IDC_BTN_VULFIX_SCAN_CANCEL              1001
#define IDC_IMG_VULFIX_SCAN_ANIMATION           1002
#define IDC_DIV_VULFIX_DISPLAY_LIST_AND_DETAIL  1003
#define IDC_LST_VULFIX_RESULT_LIST              1004
#define IDC_LST_VULFIX_FIXING_LIST              1005
#define IDC_TXT_VULFIX_VUL_DESCRIPTION          1006
#define IDC_DIV_VULFIX_RESULT_SPLITTER          1007
#define IDC_LBL_VULFIX_RESULT_CHECK_ALL         1008
#define IDC_LBL_VULFIX_RESULT_UNCHECK_ALL       1009
#define IDC_LBL_VULFIX_RESULT_CHECK_ALL_SLASH   1010
#define IDC_LBL_VULFIX_RESULT_CHECK_OPTIONAL    1011
#define IDC_LBL_VULFIX_RESULT_IGNORE            1012
#define IDC_LBL_VULFIX_RESULT_RESCAN            1013
#define IDC_LBL_VULFIX_RESULT_FIX               1014
#define IDC_LBL_VULFIX_SHOW_IGNORED_DLG         1015
#define IDC_LBL_VULFIX_SHOW_INSTALLED_DLG       1016
#define IDC_LBL_VULFIX_SHOW_SUPERSEDED_DLG      1017
#define IDC_LBL_VULFIX_SHOW_INVALID_DLG      1218		// ## 

#define IDC_DIV_VULFIX_REPAIR_TOP_INIT			1018
#define IDC_DIV_VULFIX_REPAIR_TOP_DONE			1019
#define IDC_DIV_VULFIX_REPAIR_TOP_DONE_PART		1020
#define IDC_DIV_VULFIX_REPAIR_TOP_FAILED		1021
#define IDC_PROGRESS_VULFIX_REPAIR				1022
#define IDC_LBL_VULFIX_REPAIR_TOP_CANCEL		1023
#define IDC_LBL_VULFIX_REPAIR_TOP_BACKRUN		1024
#define IDC_CHK_VULFIX_REPAIR_TOP_DONERESTART	1025
#define IDC_LBL_VULFIX_REPAIR_TOP_REBOOT		1026
#define IDC_LBL_VULFIX_REPAIR_TOP_RESCAN		1027
#define IDC_LBL_VULFIX_REPAIR_TOP_REBOOT2		1028
#define IDC_LBL_VULFIX_REPAIR_TOP_RESCAN2		1029
#define IDC_LBL_VULFIX_REPAIR_TOP_RESCAN3		1030
#define IDC_LBL_VULFIX_ERROR_REPAIR				1031
#define IDC_DIV_VULFIX_RIGHT_SHOW_SEL_NONE		1032
#define IDC_DIV_VULFIX_RIGHT_SHOW_SELECT		1033
#define IDC_TXT_VULFIX_ALL_DWON_KB_SIZE			1034
#define IDC_DIV_VULFIX_IGNORE_BTM_CK			1036

#define IDC_DIV_VULFIX_REPAIR_BTM_INIT			1037
#define IDC_DIV_VULFIX_REPAIR_BTM_DONE			1038
#define IDC_DIV_VULFIX_REPAIR_BTM_DONE_PART		1039
#define IDC_DIV_VULFIX_REPAIR_BTM_FAILED		1040
#define IDC_TXT_VULFIX_REPAIR_SCAN_RES_TIP		1041


//////////////////////////////////////////////////////////////////////////
// 4000-4999 系统优化，开机启动项优化

#define IDC_TAB_SYSOPT_LEFT						4001
#define IDC_DIV_SYSOPT_RUN						4002
#define IDC_LST_RUNOPT							4003
#define IDC_TAB_RUNOPT_TYPE						4004
#define IDC_LBL_RUNOPT_SHOW_ENABEL				4005
#define IDC_LBL_RUNOPT_SHOW_DISABLE				4006
#define IDC_LBL_RUNOPT_SHOW_ALL					4007
#define IDC_LBL_RUNOPT_HIDE_SYSTEM				4008
#define IDC_LBL_RUNOPT_SHOW_SYSTEM				4009
#define IDC_DIV_RUNOPT_CONTROL_SYS				4010
#define IDC_LBL_RUNOPT_REFRESH					4011
#define IDC_BTN_RUNOPT_CANCEL_ALL				4012
#define IDC_DIV_RUNOPT_BOTTOM					4013
#define IDC_TABPAGE_RUNOPT_START				4014
#define IDC_TABPAGE_RUNOPT_SERVICE				4015
#define IDC_TABPAGE_RUNOPT_TASK					4016
#define IDC_DIV_SYSOPT_MORE						4017
#define IDC_BTN_SYSOPT_WAIT_MORE				4018
#define IDC_DIV_RUNOPT_TOP_RUN					4019
#define IDC_DIV_RUNOPT_TOP_SERVICE				4020
#define IDC_DIV_RUNOPT_TOP_TASK					4021
#define IDC_LBL_RUNOPT_TOP_MORE					4022
#define IDC_DIV_RUNOPT_BTM_RUN_JOB_OP			4023
#define IDC_LBL_RUNOPT_BTM_SERVICE_OP			4024
#define IDC_LBL_RUNOPT_SHOW_ENABEL2				4025
#define IDC_LBL_RUNOPT_SHOW_DISABLE2			4026
#define IDC_LBL_RUNOPT_SHOW_ALL2				4027
#define IDC_DIV_SYSOPT_CLR_HISTORY				4028

#define IDC_DIV_CLR_NO_DOWN						4029
#define IDC_DIV_CLR_DOWNING						4030
#define IDC_DIV_CLR_INSTALLED					4031
#define IDC_TXT_CLR_NO_DOWN						4032
#define IDC_BTN_CLR_DOWN_PACK					4033
#define IDC_TXT_CLR_NO_DOWN_TOP_TIP				4034
#define IDC_ICON_CLR_NO_DOWN_TOP_TIP			4035

#define IDC_TAB_CLR_TOP							4400
#define IDC_DIV_CLR_TOP_PANL					4401
#define IDC_IMG_SETTING							4402
#define IDC_BTN_CRL_SETTING						4403

#define IDC_TXT_CLR_STATE						4404
#define IDC_TXT_CLR_STATE_DATE					4405
#define IDC_TXT_CLR_STATE_SIZE					4406
#define IDC_TXT_CLR_STATE_ALLSIZE				4407
#define IDC_TXT_CLR_SCAN_OPR					4408
#define IDC_CHK_CLR_SCAN_HENJI					4409
#define IDC_CHK_CLR_SCAN_LAJI					4410
#define IDC_CHK_CLR_SCAN_ZHUCEBIAO				4411
#define IDC_DIV_CLR_PANL						4412
#define IDC_DIV_CLR_SCAN						4413
#define IDC_DIV_CLR_SCANING						4414
#define IDC_IMG_CLR_SCANING						4415
#define IDC_TXT_CLR_SCANING						4416
#define IDC_PRO_CLR_SCANING						4417
#define IDC_BTN_CLR_STOP_SCANING				4418

#define IDC_DIV_CLR_GAOJI						4419
#define IDC_TREE_CLR_GAOJI						4420
#define IDC_DIV_CLR_TREETOP						4421
#define IDC_DIV_CLR_TREEDOWN					4422
#define IDC_IMG_CLR_TREETOP						4423
#define IDC_TXT_CLR_TREETOP						4424
#define IDC_DIV_CLR_TREEDOWNBTN					4425
#define IDC_TXT_CLR_TREEDOWN_DAFU				4426
#define IDC_TXT_CLR_TREEDOWN_ONE				4427
#define IDC_BTN_CLR_TREEDOWNBTN_SCAN			4428
#define IDC_BTN_CLR_TREEDOWNBTN_CLEAN			4429
#define IDC_DIV_CLR_TREEDOWNBTNRESCAN			4430
#define IDC_BTN_CLR_TREEDOWNBTNRESCAN			4431
#define IDC_BTN_CLR_TREEDOWNBTN_CLEAN1			4432
#define IDC_TREE_CLR_LAJI						4433
#define IDC_TREE_CLR_REG						4434
#define IDC_DIV_CLR_LAJI						4435
#define IDC_DIV_CLR_REG							4436

#define IDC_DIV_CLR_LAJI_TREETOP				4437
#define IDC_IMG_CLR_LAJI_TREETOP				4438
#define IDC_TXT_CLR_LAJI_TREETOP				4439
#define IDC_DIV_CLR_LAJI_TREEDOWN				4440
#define IDC_TXT_CLR_LAJI_TREEDOWN_DAFU			4441
#define IDC_TXT_CLR_LAJI_TREEDOWN_ONE			4442
#define IDC_DIV_CLR_LAJI_TREEDOWNBTN			4443
#define IDC_BTN_CLR_LAJI_TREEDOWNBTN_SCAN		4444
#define IDC_BTN_CLR_LAJI_TREEDOWNBTN_CLEAN		4445
#define IDC_DIV_CLR_LAJI_TREEDOWNBTNRESCAN		4446
#define IDC_BTN_CLR_LAJI_TREEDOWNBTNRESCAN		4447
#define IDC_BTN_CLR_LAJI_TREEDOWNBTN_CLEAN1		4448

#define IDC_DIV_CLR_REG_TREETOP					4449
#define IDC_IMG_CLR_REG_TREETOP					4450
#define IDC_TXT_CLR_REG_TREETOP					4451
#define IDC_DIV_CLR_REG_TREEDOWN				4452
#define IDC_TXT_CLR_REG_TREEDOWN_DAFU			4453
#define IDC_TXT_CLR_REG_TREEDOWN_ONE			4454
#define IDC_DIV_CLR_REG_TREEDOWNBTN				4455
#define IDC_BTN_CLR_REG_TREEDOWNBTN_SCAN		4456
#define IDC_BTN_CLR_REG_TREEDOWNBTN_CLEAN		4457
#define IDC_DIV_CLR_REG_TREEDOWNBTNRESCAN		4458
#define IDC_BTN_CLR_REG_TREEDOWNBTNRESCAN		4459
#define IDC_BTN_CLR_REG_TREEDOWNBTN_CLEAN1		4460
#define IDC_TXT_CLR_REG_TREEDOWN_REREG			4461
#define IDC_CHECK_CLR_REG						4462
#define IDC_CHECK_CLR_LAJI						4463

#define IDC_DIV_CLR_SCAN_TOP					4464
#define IDC_IMG_CLR_SCAN_TOP					4465
#define IDC_TXT_CLR_SCAN_INFO1					4466
#define IDC_TXT_CLR_SCAN_INFO2					4467
#define IDC_DIV_CLR_SCAN_LISTDOWN				4468
#define IDC_BTN_CLR_SCAN_RESCAN					4469
#define	IDC_BTN_CLR_SCAN_RECOME					4470
#define IDC_LST_CLR_SCAN						4471
#define IDC_DIV_CLR_SCAN_LST					4472
#define IDC_CHECK_CLR_HENJI						4473
#define IDC_IMG_CLR_HENJI_SCAN_TREETOP			4474
#define IDC_IMG_CLR_LAJI_SCAN_TREETOP			4475
#define IDC_IMG_CLR_REG_SCAN_TREETOP			4476
#define IDC_DIV_CLR_LOADERROR					4478
#define IDC_TXT_CLR_REG_TREEDOWN_SHOWDAFU			4479
#define IDC_TXT_CLR_LAJI_TREEDOWN_SHOWDAFU			4480
#define IDC_TXT_CLR_HENJI_TREEDOWN_SHOWDAFU			4481

#define IDC_IMG_CLR_TREETOP2                    4482
#define IDC_BTN_CLR_TREEDOWNBTN_SCAN_START      4483
#define IDC_TXT_CLR_HENJI_SHOW_EX1              4484
#define IDC_TXT_CLR_HENJI_SHOW_EX2              4485
#define IDC_TXT_CLR_HENJI_SHOW_EX3              4486
#define IDC_TXT_CLR_TREETOP2                    4487

#define IDC_BTN_RUNOPT_AUTO_OPT					4111

//////////////////////////////////////////////////////////////////////////
// 实时保护

#define IDC_IMG_PROTECTION_STAT_BROWSERTPROTECT         5028
#define IDC_TXT_PROTECTION_BROWSERTPROTECT1				5029
#define IDC_TXT_PROTECTION_BROWSERTPROTECT2				5030
#define IDC_TXT_PROTECTION_TURN_ON_BROWSERTPROTECT      5031
#define IDC_TXT_PROTECTION_TURN_OFF_BROWSERTPROTECT     5032
#define IDC_LBL_PROTECTION_TURN_OFF_BROWSERTPROTECT     5033
#define IDC_LBL_PROTECTION_TURN_ON_BROWSERTPROTECT      5034
#define IDC_LBL_PROTECTION_STATUS_BROWSERTPROTECT       5035
#define IDC_IMG_PROTECTION_STAT_BWSP_PHISHING           5036
#define IDC_TXT_PROTECTION_BWSP_PHISHING1				5037
#define IDC_TXT_PROTECTION_BWSP_PHISHING2				5038
#define IDC_TXT_PROTECTION_TURN_ON_BWSP_PHISHING        5039
#define IDC_TXT_PROTECTION_TURN_OFF_BWSP_PHISHING       5040
#define IDC_LBL_PROTECTION_TURN_OFF_BWSP_PHISHING       5041
#define IDC_LBL_PROTECTION_TURN_ON_BWSP_PHISHING        5042
#define IDC_LBL_PROTECTION_STATUS_BWSP_PHISHING         5043
#define IDC_LBL_PROTECTION_BWSP_MORE_SETTING1           5044
#define IDC_LBL_PROTECTION_BWSP_MORE_SETTING2           5045

//////////////////////////////////////////////////////////////////////////
// 一键优化的对话框
#define IDC_BTN_RUN_AUTO_CLOSE					1
#define IDC_LST_RUN_AUTO_OPT					2
#define IDC_LBL_RUN_AUTO_CHECK_ALL				3
#define IDC_LBL_RUN_AUTO_UNCHECK_ALL			4
#define IDC_BTN_RUN_AUTO_DO						5
#define IDC_DIV_RUN_AUTO_HAVE					6
#define IDC_DIV_RUN_AUTO_NO						7
#define IDC_BTN_RUN_AUTO_CANCEL					8
#define IDC_DIV_RUN_AUTO_BTM_INIT				9
#define IDC_DIV_RUN_AUTO_BTM_DONE				10
#define IDC_DIV_RUN_AUTO_TOP_INIT				11
#define IDC_DIV_RUN_AUTO_TOP_SUCCESS			12
#define IDC_DIV_RUN_AUTO_TOP_FAILED				13
#define IDC_BTN_RUN_AUTO_BTM_CLOSE				14



//////////////////////////////////////////////////////////////////////////
//Setup 对话框
#define IDC_BTN_SETUP_CLOSE						1
#define IDC_PROGRESS_SETUP						3
#define IDC_BTN_SETUP_CANCEL					4

//////////////////////////////////////////////////////////////////////////
// 发现病毒同时发现未知文件的对话框
#define IDC_BTN_REPORT                          100
#define IDC_RICHTEXT_CONTENT                    101
#define IDC_LBL_VIEW_DETAIL                     102

//////////////////////////////////////////////////////////////////////////
// 安装毒霸引擎对话框

#define IDC_PROGRESS_INSTALL                    100
#define IDC_BTN_INSAVE_MINIMIZE                 101
#define IDC_BTN_INSAVE_CANCEL                   102
#define IDC_LBL_PROGRESS                        103
#define IDC_LST_INSTALL_PROGRESS_DETAIL         104
#define IDC_BTN_INSAVE_FINISH                   105
#define IDC_DIV_INSAVE_WORKING                  106
#define IDC_DIV_INSAVE_FINISH                   107

//////////////////////////////////////////////////////////////////////////
// 软件管理设置对话框
#define IDC_SETTING_LIST						100
#define IDC_DLG_DOWNLOAD_SET					101
#define IDC_DLG_INSTALL_SET						102
#define IDC_DLG_DELFILE_SET						103
#define IDC_LINKTEXT_OPEN_DIR					201
#define IDC_EDIT_STORE_DIR						202
#define IDC_IMGBTN_SELECT_DIR					203
#define IDC_LINKTEXT_DEFAULT_DIR				204
#define IDC_LBL_DISK_SPACE						205
#define IDC_CHECK_SHOWHINT						206
#define IDC_CHECK_NO_HINT						207
#define IDC_CHECK_AUTO_INSTALL					208
#define IDC_CHECK_NO_AUTO_INSTALL				209
#define IDC_CHECK_DEL_WEEK						210
#define IDC_CHECK_DEL_RIGHTNOW					211
#define IDC_CHECK_DEL_NEVER						212
#define IDC_CHECK_DEL_TO_RECY					220
#define IDC_CHECK_DEL_REAL						221

//////////////////////////////////////////////////////////////////////////
// 下载管理对话框
#define IDC_DOWNMGR_LEFT_LIST					100
#define IDC_DOWNMGR_ING_DLG						101
#define IDC_DOWNMGR_ING_DESC					102
#define IDC_DOWNMGR_ING_BTN_DIR					103
#define IDC_DOWNMGR_ING_LNK_DIR					104
#define IDC_DOWNMGR_ING_RIGHT_LIST				105
#define IDC_DLG_ING_NO_ITEM						106
#define IDC_DOWNMGR_ED_DLG						200
#define IDC_DOWNMGR_ED_DESC						201
#define IDC_DOWNMGR_ED_BTN_DIR					202
#define IDC_DOWNMGR_ED_LNK_DIR					203
#define IDC_DOWNMGR_ED_RIGHT_LIST				204
#define IDC_DOWNMGR_ED_CHECK					205
#define IDC_DOWNMGR_ED_TXT_CHECK				206
#define IDC_DOWNMGR_ED_BTN_DEL					207
#define IDC_DLG_ED_NO_ITEM						208
//垃圾箱
#define IDC_DOWNMGR_RUBBISH_RIGHT_LIST			209
#define IDC_DOWNMGR_RUBBISH_CHECK				210
#define IDC_DOWNMGR_RUBBISH_BTN_DEL				211
#define IDC_DOWNMGR_RUBBISH_NO_ITEM				212
#define IDC_DOWNMGR_RUBBISH_TEXT_DESC			213
#define IDG_DOWNMGR_RUBBISH_DLG					214

#define IDC_DOWNMGR_ING_DESC_FMT				9910
#define IDC_DOWNMGR_ED_DESC_FMT					9911
#define IDC_DOWNMGR_ING_DESC_FMT0				9921
#define IDC_DOWNMGR_ED_DESC_FMT0				9922
#define IDS_DOWNMGR_RUBBISH_FMT					9923
#define IDS_DOWNMGR_RUBBISH_FMT0				9924

//////////////////////////////////////////////////////////////////////////
// 添加恶意网址对话框
#define IDC_DLG_ADD_URL_BTN_OK					100
#define IDC_DLG_ADD_URL_BTN_CANCEL				101
#define IDC_DLG_ADD_URL_REALWND					102



//////////////////////////////////////////////////////////////////////////
// STRING ID

#define IDS_APP_NAME                            1
#define IDS_EXAM_SCORE                          2
#define IDS_LIST_VIRUS_COLUMN_VIRUS_NAME_TITLE  3
#define IDS_LIST_VIRUS_COLUMN_FILE_NAME_TITLE   4
#define IDS_LIST_VIRUS_COLUMN_VIRUS_STAT_TITLE  5
#define IDS_EXAM_LEVEL_DANGER                   6
#define IDS_EXAM_TEXT_DANGER                    7
#define IDS_EXAM_LEVEL_RISK                     8
#define IDS_EXAM_TEXT_RISK                      9
#define IDS_EXAM_LEVEL_SAFE                     10
#define IDS_EXAM_TEXT_SAFE                      11
#define IDS_SCANNED_FILE_COUNT_FORMAT           12
#define IDS_VIRUS_COUNT_FORMAT                  13
#define IDS_SCANNED_TIME_COUNT_FORMAT           14
#define IDS_EXAM_LEVEL_CANCELED                 15
#define IDS_EXAM_TEXT_CANCELED                  16
#define IDS_MSGBOX_BUTTON_XML                   17
#define IDS_MSGBOX_OK                           18
#define IDS_MSGBOX_CANCEL                       19
#define IDS_MSGBOX_ABORT                        20
#define IDS_MSGBOX_RETRY                        21
#define IDS_MSGBOX_IGNORE                       22
#define IDS_MSGBOX_YES                          23
#define IDS_MSGBOX_NO                           24
#define IDS_MSGBOX_CONTINUE                     25
#define IDS_MSGBOX_BUTTON_DIV                   26
#define IDS_FOUND_VIRUS_TITLE                   27
#define IDS_FILE_STATE_NOCLEAN                  28
#define IDS_FILE_STATE_DELETESUCCESS            29
#define IDS_FILE_STATE_REPAIRSUCCESS            30
#define IDS_FILE_STATE_DELETEFAILED             31
#define IDS_FILE_STATE_REPAIRFAILED             32
#define IDS_FILE_STATE_DELETEREBOOT             33
#define IDS_FILE_STATE_REPAIRREBOOT             34
#define IDS_FILE_STATE_NEEDCLEAN                35
#define IDS_FILE_STATE_CANNOTCLEAN              36
#define IDS_FILE_STATE_SAFE                     37
#define IDS_FILE_STATE_SCANFAILURE              38
#define IDS_FOUND_VIRUS_ALL_CLEANED_TITLE       39
#define IDS_FOUND_VIRUS_NEED_REBOOT_TITLE       40
#define IDS_REMAIN_VIRUS_COUNT_FORMAT           41
#define IDS_SCANNING_STEP_FORMAT                42
#define IDS_PROTECTION_STATUS_ON                43
#define IDS_PROTECTION_STATUS_OFF               44
#define IDS_VIRSCAN_LAST_SCAN_LESS_THAN_1MIN    45
#define IDS_VIRSCAN_LAST_SCAN_MINUTES           46
#define IDS_VIRSCAN_LAST_SCAN_HOURS             47
#define IDS_VIRSCAN_LAST_SCAN_DAYS              48
#define IDS_VIRSCAN_LAST_SCAN_INFO_RICH_TEXT    49
#define IDS_VIRSCAN_QUARANTINE_COUNT            50
#define IDS_VIRSCAN_REPORTED_UNKNOWN_COUNT      51
#define IDS_VIRSCAN_FOUND_UNKNOWN_NOTICE_CONTENT    52
// #define IDS_VIRSCAN_DYNAMIC_NOTICE_NEED_UPDATE  53
#define IDS_VIRSCAN_DYNAMIC_NOTICE_FAST_SCAN    54
// #define IDS_VIRSCAN_DYNAMIC_NOTICE_FULL_SCAN    55
#define IDS_EXAM_TEXT_NOT_SET_AUTO_EXAM         56
#define IDS_EXAM_TEXT_EXAM_NOW                  57
#define IDS_VIRSCAN_SETTING_AUTOCLEAN           58
#define IDS_VIRSCAN_SETTING_MANUALCLEAN         59
#define IDS_EXAM_TEXT_EXAM_AGAIN                60
#define IDS_PROTECTION_LOG_COUNT                61
#define IDS_FOUND_VIRUS_REMAINED_TITLE          62
#define IDS_EXAM_TEXT_CANCELED_SAFE				63
#define IDS_NOT_FOUND_VIRUS_TITLE               64
#define IDS_EXAM_CANCEL_INFO_SAFE				65
#define IDS_EXAM_CANCEL_INFO_UNSAFE				66
#define IDS_EXAM_SCAN_INFO_SAFE					67
#define IDS_EXAM_SCAN_INFO_RASIK				68
#define IDS_EXAM_SCAN_INFO_DANGER				69
#define IDS_EXAM_SCAN_HISTORY_ERROR				70


//软件管理
#define IDC_LIST_SOFTMGR					8100
#define IDC_EDIT_SOFTMGR					8101
#define IDC_SETTING_SOFTMGR					8102
#define IDC_REFRESH_SOFTMGR					8103
#define IDC_QUERY_SOFTMGR					8104
#define IDC_SETTING_PNG_SOFTMGR				8105
#define IDC_REFRESH_PNG_SOFTMGR				8106
#define IDC_DOWNLOADMGR_SOFTMGR				8107
#define IDC_BATCHDOWN_SOFTMGR				8108
#define IDC_TEXT_SELECTALL					8109
#define IDC_TEXT_SELECTFREENOPLUG			8110
#define IDC_TEXT_DETAIL_DOWNLAOD			8111
#define IDC_SHOW_NOPLUG_SOFTMGR				8112
#define IDC_CHECKBOX_SELECT_FREESOFT		8113
#define IDC_DETAILBK_SOFTMGR				8114
#define IDC_DLG_INSTALL_SOFTMGR				8115
#define IDC_DLG_DETAIL_SOFTMGR				8116
#define IDS_TEXT_FORMAT_DETAIL_SOFTMGR		8117
#define IDS_TEXT_NAME_DETAIL_SOFTMGR		8118
#define IDS_BACK_DETAIL_SOFTMGR				8119
#define IDS_INFO_FORMAT_SOFTMGR				8120
#define IDS_INFO_SOFTMGR					8121
#define IDG_ICON_DETAIL_SOFTMGR				8122
#define IDS_FREE_DETAIL_SOFTMGR				8123
#define IDS_PLUG_DETAIL_SOFTMGR				8124
#define IDS_FITAYATEM_DETAIL_SOFTMGR		8125
#define IDC_DOWN_BTN_DETAIL_SOFTMGR			8126
#define IDC_IE_DETAIL_SOFTMGR				8127
#define IDC_TYPES_LEFT_SOFTMGR				8128
#define IDC_ICON_FREE_DETAIL_SOFTMGR		8129
#define IDC_ICON_PLUG_DETAIL_SOFTMGR		8130
#define IDC_ICON_FITAYATEM_DETAIL_SOFTMGR	8131
#define IDC_TAB_SOFTMGR						8132
#define IDC_FREEBACK_SOFTMGR				8133
#define IDR_FIND_QUERY_SOFTMGR				8134
#define IDC_BACK_QUERY_SOFTMGR				8135
#define IDS_TIP_QUERY_SOFTMGR				8136
#define IDS_NOFIND_QUERY_SOFTMGR			8137
#define IDS_NOFIND_TIP_SOFTMGR				8138
#define IDS_RESULT_QUERY_SOFTMGR			8139
#define IDS_NO_QUERY_SOFTMGR				8140
#define IDS_NOFIND_TIP2_SOFTMGR				8141
#define IDS_LINK_TIP2_SOFTMGR				8142
#define IDS_LINK_SUBMIT_SOFTMGR				8143
#define IDG_LOAD_TIP_SOFTMGR				8144
#define IDC_LOAD_PIC_SOFTMGR				8145
#define IDC_LOADINFO_PIC_SOFTMGR			8146
#define IDC_LOADINFO_PIC1_SOFTMGR			8147
#define IDC_LOAD_PIC1_SOFTMGR				8148
#define IDC_LOAD_TIPPIC_SOFTMGR				8149
#define IDG_QUERY_BAR_SOFTMGR				8150   //搜索面板

#define IDC_DLG_PROG1						8201
#define	IDC_PROG_INIT1						8202
#define IDC_DLG_PROG2						8205
#define	IDC_PROG_INIT2						8206
#define IDC_LOAD_TIP1						8207
#define IDC_LOAD_TIP2						8208

// 软件卸载首页
#define IDC_DLG_UNI_STARTPAGE				8210
#define IDC_TXT_UNI_TITLE					8211
#define IDC_BTN_UNI_ALL						8212
#define IDC_BTN_UNI_DESK					8213
#define IDC_BTN_UNI_STARTMENU				8214
#define IDC_BTN_UNI_QUICKLAN				8215
#define IDC_BTN_UNI_PROCESS					8216
#define IDC_BTN_UNI_TRAY					8217

#define IDC_DLG_UNI_CONTENT					8220	

#define IDC_LNK_STARTPAGE					8231
#define IDC_LNK_CUR_PAGE					8233
#define IDC_TXT_DETAIL_ARROW				8234
#define IDC_LNK_DETAIL						8235
#define IDC_IMG_GOBACK						8236
#define IDC_LNK_GOBACK						8237
#define IDC_BTN_SORT_BY_SPACE				8238
#define IDC_BTN_SORT_BY_TIME				8239
#define IDC_TXT_SPACE_CAP					8240
#define IDC_TXT_TIME_CAP					8241
#define IDC_IMG_SPACE_ARROW					8242
#define IDC_IMG_TIME_ARROW					8243
#define IDC_UNINSTALL_QUERYBACK_IMG			8244
#define IDC_UNINSTALL_QUERYBACK_LNK			8245


// 软件卸载
#define	IDC_UNINSTALL_TYPELIST				9000
#define IDC_UNINSTALL_SOFT_DLG				9100
#define IDC_UNINSTALL_SOFTLIST				9101
#define	IDC_DLG_SEARCH_HINT					9102
#define IDC_BTN_SEARCH_GOBACK				9103
#define IDC_TXT_SEARCH_DESC					9104
#define IDC_TXT_SEARCH_DESC_FMT				9920
#define IDC_DLG_SEARCH_CONTENT				9105
#define IDC_TXT_SEARCH_CON1					9106
#define IDC_TXT_SEARCH_CON2					9107
#define IDC_TXT_SEARCH_CON3					9108

#define IDC_UNINSTALL_SOFT_DETAIL			9200
#define IDC_BTN_UNINSTALL_DETAIL_GOBACK		9201
#define	IDC_LBL_UNINSTALL_SOFT_VIEWING		9202
#define IDC_ICO_UNINSTALL_SOFT				9203
#define IDC_LBL_UNINSTALL_SOFT_NAME			9204
#define IDC_LINK_UNINSTALL_OPENDIR			9205
#define IDC_BTN_UNINSTALL_DO				9206
#define IDC_IE_UNINSTALL					9207
#define IDC_LINK_WHAT_TO_UNINSTALL			9301
#define IDC_LBL_UNINSTALL_TOTAL				9302
#define IDC_LINK_RPT_CANT_UNINSTALL			9303
#define IDC_LNK_CALC_SPACE					9304
#define IDC_TXT_CALCING_SPACE				9305
#define IDC_TXT_CALCING_PERCENT				9306
#define IDC_LNK_CALC_CANCEL					9307
#define IDC_LNK_WATCH_LASTUSE				9310

#define IDS_LBL_UNINSTALL_SOFT_FMT			9901
#define IDS_LBL_UNINSTALL_SOFT_N_FMT		9902
#define IDS_LBL_UNINSTALL_TOTAL_FMT			9912


// 强力清扫
#define IDC_BTN_DEL_SELECTED				10001
#define	IDC_PROG_POWERSWEEP					10002
#define IDC_TXT_INTRO_PS					10003
#define	IDC_TREE_PS_ITEMS					10004
#define IDC_TXT_CLEAN_OVER					10005
#define IDS_TXT_INTRO_PS_FMT				9903
#define IDC_TXT_CLEAN_OVER_FMT				9904
#define IDC_TEXT_TIP_POWERSWEEP				9905
#define IDC_TEXT_TITTLE_POWERSWEEP			9906



